### ISSUE TITLE
Flame name conflict

### ISSUE THREAD

**Issue by kurtome** [phoenixframework/flame#14]
This project looks really cool, but it's a bit unfortunate that the name conflicts with another really big and very active open source project with a logo that looks identical: https://github.com/flame-engine/flame

Are there any options for clarifying the name, like "Phoenix Flame" or something?

**Comment by josevalim** [comment]
Name overlaps are very common. Given those projects are in different languages and have different targets (web/server vs game), I believe there isn't much to worry about. Thanks!

**Comment by josevalim** [comment]
I checked your GitHub and it seems you are the intersection of both communities in the venn diagram. :D I understand the request but I think generally speaking there should not be much confusion.
