### ISSUE TITLE
Allow spec'ing backends from pool config or call site

### ISSUE THREAD

**Issue by Doerge** [phoenixframework/flame#34]
Use case:
I have very asymmetric workloads, and I want to save costs by right-sizing the FLAME instances running the workloads.

As far as I understand, I can only spec resources in the Backend config right now, like:
```elixir
  config :flame, FLAME.FlyBackend,
    token: System.fetch_env!("FLY_API_TOKEN"),
    cpus: 8,
    memory_mb: 8 * 1024
```
I'd like to be able to do it on the pool level like this:
```elixir
      {FLAME.Pool,
       name: MyApp.FFMpegRunner,
       cpus: 8,
       memory_mb: 8 * 1024
      }
```
or maybe like this?
```elixir
      {FLAME.Pool,
       name: MyApp.FFMpegRunner,
       backend_opts: [
           cpus: 2,
           memory_mb: 8 * 1024
         ]
      }
```
or alternatively add some option in the `call`, `cast`, `place_child`.

**Comment by vhyza** [comment]
Hi @Doerge, 

I think it is already possible using `FLAME.Pool` configuration. I have in `application.ex` something like this to start 16GB Fly machine:

```elixir
 children = [
  {DNSCluster, query: Application.get_env(:grid_importer, :dns_cluster_query) || :ignore},
  {
    FLAME.Pool,
    name: SomePoolName,
    min: 0,
    max: 1,
    max_concurrency: 1,
    single_use: true,
    log: :debug,
    idle_shutdown_after: 5_000,
    backend: {
      FLAME.FlyBackend,
      token: System.fetch_env!("FLY_API_TOKEN"),
      cpu_kind: "shared",
      cpus: 8,
      memory_mb: 16384,
      env: %{
        "DNS_CLUSTER_QUERY" => System.fetch_env!("DNS_CLUSTER_QUERY"),
        "MIX_ENV" => System.fetch_env!("MIX_ENV")
      }
    }
  }
]
```

And it seems to work. I'm using version `0.1.12`...

**Comment by chrismccord** [comment]
yes you can pass the backend module/opts directly to the pool exactly as @vhyza showed. Would love a doc PR with examples. Thanks!

**Comment by Doerge** [comment]
Thank you @vhyza and Chris. Exactly what I was searching for!
